data_paths:
  raw: "data/raw/"
  processed: "data/processed/"
  features: "data/features/"
  codecfake: 
    zip_files: "data/raw/codecfake/zip"
    audio_files: "data/raw/codecfake/audio"
    label_files: "data/raw/codecfake/label"
    cache_files: "data/raw/codecfake/cache"
    features: "data/features/codecfake"
  wavefake:
    zip_files: "data/raw/wavefake/zip"
    audio_files: "data/raw/wavefake/audio"
    cache_files: "data/raw/wavefake/cache"
    features: "data/features/wavefake"
    
huggingface_repo_id:
  codecfake: "ajaykarthick/codecfake-audio"
  wavefake: "ajaykarthick/wavefake-audio"