# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set environment variables to prevent Python from writing pyc files to disc and to buffer stdout and stderr
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /mlflow

# Install MLflow
RUN pip install mlflow

# Expose port for MLflow
EXPOSE 5001

# Command to run MLflow server
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5001"]
